### ISSUE TITLE
Compatibility errors with requirements.txt

### ISSUE THREAD

**Issue by foxx** [waxnet/GreenLog#1]
First of all, thanks for releasing this tool, it's saved me a lot of work!

The `requirements.txt` will cause `python-magic` calls to fail due to version differences. By removing the entry for `python-magic` and keeping only `python-magic-bin` it was able to correctly resolve the dependancy versions and would then run properly.

I've generated a `Pipfile` for this which you may want to use instead (makes venv much easier).

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
python-magic-bin = "*"
keyboard = "*"
watchdog = "*"
requests = "*"
pystyle = "*"
psutil = "*"

[requires]
python_version = "3.11"
```

**Comment by foxx** [comment]
Also there's a bug with dynamic dumping.. the status is updated via `title` but when using Terminal for Windows, it seems to only update a few times then stalls, this gives the impression that it has hung but it hasnt.

To this fix, I just changed it to a print statement instead:

```
while data.timeout > 0:
  print(f"title GreenLog - {data.timeout} seconds left - {data.resets} timer resets")
  data.timeout -= 1
  time.sleep(1)
```

**Comment by foxx** [comment]
![image](https://github.com/waxnet/GreenLog/assets/651797/9f49735f-b3aa-4aee-9bd4-be8c8d5dd033)

^ As you can see, the title does not get updated (I left in the cmd.execute in my version, along with the print, but the title still did not update. It's dumping fine though)

**Comment by waxnet** [comment]
Thank you very much for reporting these issues. I will analyze and fix them as soon as possible.

I believe the bug with the dynamic dump status is caused by the Windows Terminal itself since GreenLog was developed on Windows 10 for CMD. If you could play around with it and find a solution, it would greatly help.

As for the requirements bug, I already knew that the magic module had some installment issues, and I will try to use the pipfile that you made in an attempt to fix it.

Thanks again for your help!
